### ISSUE TITLE
github ssh urls fail

### ISSUE THREAD

**Issue by chonthu** [Masterminds/vcs#10]
TestVCSLookup Test Fails:

When I try the default github ssh urls:

"git@github.com:Masterminds/VCSTestRepo.git":                       {work: true, t: Git},

**Comment by mattfarina** [comment]
The auto-detection is based on [URLs](https://en.wikipedia.org/wiki/Uniform_Resource_Locator). An ssh location, such as `git@github.com:Masterminds/VCSTestRepo.git`, isn't a url which is what causes the problem. It's a host plus a path.

It would be useful for the auto-detection to pickup ssh remotes as they are common. Currently, if you use the `NewGitRepo` function it will work with ssh remote since it isn't trying to auto-detect the type.

**Comment by chonthu** [comment]
Would you like for me to build that as a pr? I already have a working fork that just needs some cleanup

Best,

Nithin Meppurathu





On Wed, Dec 16, 2015 at 9:18 PM -0800, "Matt Farina" <notifications@github.com> wrote:












The auto-detection is based on URLs. An ssh location, such as git@github.com:Masterminds/VCSTestRepo.git, isn't a url which is what causes the problem. It's a host plus a path.



It would be useful for the auto-detection to pickup ssh remotes as they are common. Currently, if you use the NewGitRepo function it will work with ssh remote since it isn't trying to auto-detect the type.

**Comment by mattfarina** [comment]
I would appreciate the pull request. Thanks for your willingness.

**Comment by ultimateboy** [comment]
As a temporary work around, I simply removed the check of a valid URL. https://github.com/drud/vcs/commit/e75d873a3b5272810dcc61e69a2ea12148ef3e01

Would love to have support for git ssh urls!

**Comment by chonthu** [comment]
Sorry for the delay, PR here https://github.com/Masterminds/vcs/pull/14

**Comment by mattfarina** [comment]
This should be fixed on the tip of master and in the next release.
